# Wolf OS security level: gaming. Same as the wolf level, except:
-kernel.io_uring_disabled = 0
net.ipv4.icmp_echo_ignore_all = 0
# Don't slow down programs that trigger "split locks". SteamOS does the same, because the
# slowdown makes a few games stutter badly. Only affects CPUs that detect split locks.
-kernel.split_lock_mitigate = 0
kernel.sysrq = 16
net.ipv4.tcp_timestamps = 1
